#!/bin/bash -xe
until mysqladmin -h "${MAGEDB_1_PORT_3306_TCP_ADDR}" -u root --password="${MAGEDB_1_ENV_MYSQL_ROOT_PASSWORD}" create magento; do
	sleep 1
done
php install.php \
    --admin_email admin@example.com \
    --admin_firstname ad \
    --admin_lastname min \
    --admin_password testing123 \
    --admin_username admin \
    --db_host "${MAGEDB_1_PORT_3306_TCP_ADDR}" \
    --db_name magento \
    --db_pass "${MAGEDB_1_ENV_MYSQL_ROOT_PASSWORD}" \
    --db_user root \
    --default_currency USD \
    --license_agreement_accepted yes \
    --locale en_US \
    --secure_base_url / \
    --skip_url_validation yes \
    --timezone America/New_York \
    --url / \
    --use_rewrites yes \
    --use_secure no \
    --use_secure_admin no
mysql -h "${MAGEDB_1_PORT_3306_TCP_ADDR}" -u root --password="${MAGEDB_1_ENV_MYSQL_ROOT_PASSWORD}" magento <<SQL
INSERT INTO core_config_data
SET path='web/url/redirect_to_base', value=0;
SQL
exec /usr/sbin/apache2ctl -D FOREGROUND
