#!/bin/bash

##
# Detect the ownership of the webroot
# and run apache as that user.
#
main() {
    set -x
    local owner group owner_id group_id
    cd /srv/magento
    read owner group owner_id group_id < <(stat -c '%U %G %u %g' .)
    if [[ "$owner" != "www-data" ]]; then
        userdel -f www-data || exit 1
        addgroup --system --gid "$group_id" "www-data"
        adduser --system --uid=$owner_id --gid=$group_id "www-data"
    fi
    # Not volumes, so need to be chowned
    chown -R "www-data:www-data" /var/{lock,log,run}/apache*
    exec /usr/sbin/apache2ctl "$@"
}

##
# Generate a random sixteen-character
# string of alphabetical characters
randname() {
    local -x LC_ALL=C
    tr -dc '[:lower:]' < /dev/urandom |
        dd count=1 bs=16 2>/dev/null
}

main "$@"
